### ISSUE TITLE
Support folding

### ISSUE THREAD

**Issue by joerdav** [vrischmann/tree-sitter-templ#42]
Hey, we have an issue over in templ to enable code folding via the LSP, however I use treesitter for folding but it doesn't seem to work with templ files.

Here is my config:

```
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
```

I'll take a look to see if I can add this in a PR, but just wanted to raise here incase you had any ideas!

**Comment by vrischmann** [comment]
Hi,

We didn't create a `folds.scm` file in the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/templ) queries, which is why folding doesn't work. 

As far as I can tell we just need to create this file, add it upstream (or locally to test) and folding should work ?

**Comment by joerdav** [comment]
Yes started working on this, just struggling to get my config to install the local version!

**Comment by joerdav** [comment]
Okay sorted that now! Will have the folds file done soon!
